### ISSUE TITLE
Please add new Manufacturer name to driver 1402755

### ISSUE THREAD

**Issue by JohanBendz** [easyhomesrc/homey_namronas#1]
A Namron product have a different manufacturer name but it's the same unit.
Can you please add it to the app.

Manufacturer name: Shyugj
Product ID: Dimmer-Switch-ZB3.0

![image](https://user-images.githubusercontent.com/34488771/97911661-ebc15200-1d4b-11eb-943c-7b825604fc61.png)
![image](https://user-images.githubusercontent.com/34488771/97911677-f7ad1400-1d4b-11eb-8e3d-aa0597b470f1.png)

**Comment by maginawin** [comment]
@JohanBendz 

Sorry, Homey does not allow products whose manufacturers are not "namron as" to be added to the namron App.

Will Shyugj release their Homey App? They can use the code in this repository and modify the manufacturer.

**Comment by JohanBendz** [comment]
Hi @maginawin, but this is a product in a Namron package.. to the customer this is a Namron unit, not a Shyugj. I know you have had discussions with Athom about your Easyhome app containing multiple brands but in this case I think they would agree this device is best added to this Namron app.

**Comment by maginawin** [comment]
Hi @JohanBendz 

I have communicated with Homey on this issue, they just suggested that I contact the manufacturer to release a new Homey App.

I will report your issue to Namron.

**Comment by maginawin** [comment]
Hi @JohanBendz 

Added support for this device, you can install a beta version for testing. Please remove your device before testing.

https://homey.app/a/net.filllip-namron/test/
