### ISSUE TITLE
Zigbee/z-wave 200W dimmer not updating in app when dimming locally

### ISSUE THREAD

**Issue by annern55** [easyhomesrc/homey_namronas#11]
Hello,
So this dimmer does not seem to update the status in Athom homey when you dim through the wall switch. It does not detect status on/off, nor updates itself in the app if you dim it down through the wall switch. Could you look into this please? :)
Product: 1402755 and 1402756
Mvh annern55

**Comment by maginawin** [comment]
Hi @annern55 ,

In theory, a device can broadcast its state changes to the gateway, but the device doesn't seem to do that. 

I tried to fix this, but the gateway didn't receive a state change at all.

**Comment by annern55** [comment]
> Hi @annern55 ,
> 
> In theory, a device can broadcast its state changes to the gateway, but the device doesn't seem to do that.
> 
> I tried to fix this, but the gateway didn't receive a state change at all.

That's quite weird and unfortunate :/ It makes flows quite useless when it doesn't give any feedback back to the app after being dimmed locally. No way around this that you can think of? :)

**Comment by maginawin** [comment]
Hi @annern55 ,

The latest version of the App has solved this problem, and maybe you need to re-add the device.
