### ISSUE TITLE
Is there any chance for support for the following devices?

### ISSUE THREAD

**Issue by irowan** [easyhomesrc/homey_namronas#12]
4512729 https://www.elektroimportoren.no/namron-zigbee-2-kanaler-bryter-k4-sort/4512729/Product.html
4512731 https://www.elektroimportoren.no/namron-z-wave-2-kanaler-bryter-k4-sort/4512731/Product.html
4512732 https://www.elektroimportoren.no/namron-zigbee-foh-bryter-k4-sort/4512732/Product.html

I can't find them in the app.

**Comment by maginawin** [comment]
@irowan 

We have planned to support these devices on Homey v5.0+, and I will get back to you when we are done.

**Comment by maginawin** [comment]
@irowan 

We updated the Namron App, 4512729 and 4512732 are now supported. 4512732 is made for Hue, Namron App can't support for it.

https://homey.app/a/net.filllip-namron/test/

**Comment by irowan** [comment]
That was quick. Thank you so much! :)

You should tell your guys at Namron that a multibutton like the FOH has a special appeal, since it has no markings on it. The 8 button controller would be so much better if there was only one off button. Dymo fixes this, but dymo ain't too sexy.
