### ISSUE TITLE
Move with

### ISSUE THREAD

**Issue by torsteri** [easyhomesrc/homey_namronas#13]
I'm struggling to understand the "move with (on/off)", I assume this is to be used when a button is held on the switch, but it doesn't let me distinguish between the 1-on button and the 0-off button. Any help?

**Comment by maginawin** [comment]
Hi @torsteri ,
When a button is held on, a move level with on/off event is triggered, and the event is named move level with on/off just to be consistent with the manual and doesn't trigger any on/off behavior in Homey. You can set move level with on/off to Flow's condition and press and hold the button to trigger it.

**Comment by torsteri** [comment]
Yes, that I understand, but it seems strange that the same action is then triggered if the on 9r the off button is held... Shouldn't there be two triggers, one for on and one for off?

**Comment by maginawin** [comment]
@torsteri 

Please tell me the model number of the device.

**Comment by torsteri** [comment]
4512721
Black 4 channel wall remote

**Comment by torsteri** [comment]
![45FF3171-7B73-46DE-AB55-E08618A05055](https://user-images.githubusercontent.com/74407695/105624500-7765ee80-5e22-11eb-897a-60e245319517.jpeg)

**Comment by torsteri** [comment]
Any news?

**Comment by maginawin** [comment]
Hi @torsteri ,
We use "Move mode" to identify Move level up/down, and here's a video that shows to use Move level to control the brightness of a lighting. https://youtu.be/U8DMCjpNemU
