### ISSUE TITLE
An unknown error has occured (request_timeout)

### ISSUE THREAD

**Issue by proisland** [easyhomesrc/homey_namronas#14]
I have installed a product ID 1402756, but short after installing it the device gives an error saying 'An unknown error has occured (request_timeout)' when trying to manage the device.

**Comment by maginawin** [comment]
Hi @proisland,

Can you provide the Manufacturer ID, Product Type ID, Product ID to me? They are in Device -> Settings -> Advance page.

Best regards,
Wendong Wang

**Comment by prj84** [comment]
Same issue with 4512715
