### ISSUE TITLE
Zigbee - Reporting attribute fail

### ISSUE THREAD

**Issue by prj84** [easyhomesrc/homey_namronas#19]
Attribute reporting doesn't seem to work on zigbee devices if they are controlled from an other device and not from Homey. This should be corrected by adding code provided under. This will trigger a report if any of these values are changed from another device or locally on device.

Fault is reported with device 4512700 that is controlled by zigbee remote. It then will not report any changes to Homey.

ONOFF:
await this.configureAttributeReporting([
        {
            endpointID: 1,
            cluster: CLUSTER.ON_OFF,
            attributeName: 'onOff',
            minInterval: 0,
            maxInterval: 300,
            minChange: 0,
        },
      ])

DIM:
await this.configureAttributeReporting([
  {
      endpointID: 1,
      cluster: CLUSTER.LEVEL_CONTROL,
      attributeName: 'currentLevel',
      minInterval: 0,
      maxInterval: 300,
      minChange: 0,
  },
]);

**Comment by maginawin** [comment]
@prj84 

Thank you very much for your guidance, I will add attribute reporting for all ZigBee devices.

**Comment by maginawin** [comment]
Hi @prj84 ,

I tried to add this code and it didn't work. I make the following changes in `driver.compose.json`, and the device works. I will modify all ZigBee devices. Tomorrow I can fix all the issues and the release a new App.

```
"endpoints": {
      "1": {
        "clusters": [
          0,
          3,
          4,
          5,
          6,
          8,
          2821,
          4096
        ],
        "bindings": [
          // Added 6, 8 for get attribute report
          6,
          8,
          25
        ]
      }
    },
```

**Comment by maginawin** [comment]
Hi @prj84 ,

I fixed the problem and released a new version.  
 
https://homey.app/en-us/app/net.filllip-namron/namron/test/
