### ISSUE TITLE
Available from homey app "store"?

### ISSUE THREAD

**Issue by espenjohannessen** [easyhomesrc/homey_namronas#2]
I bought a bunch of Homey, Namron and Hue stuff a few weeks back, and have been going back and forth with Namron for a while without getting anywhere since they don't have any Homey apps for their ZigBee devices. They claim to be waiting for Homey v5 to be released before releasing their app, but since so many other manufactureres have released an app with v5 support already it just seems like a poor excuse.

I then stumbled upon this repository that seems to be exactly what I'm looking for: a community driven Homey app for Namron devices with v5 support (since I'm running v5 RC38 or something like that).

1. Does it support the two Namron ZigBee devices I now have a bunch of?
    - https://www.elektroimportoren.no/led-paere-6w-rgbw-gu10-zigbee/3802967/Product.html
    - https://www.elektroimportoren.no/namron-led-dimmer-zigbee-200w/1402755/Product.html
2. Can this app be installed directly from Homey or do I have to go through the CLI install method?

**Comment by espenjohannessen** [comment]
I installed the app to my Homey Pro using the CLI install method and tried adding the two devices. Looks like the GU10 is 3802967 and the dimmer is 1402755, but I wasn't able to get any of them working. The GU10 was added, but when I tried to interact with it I got an invalid_device error message and the dimmer switch wasn't detected at all (not even added as an unknown device).

Screenshot of Advanced settings and error message for GU10:
![2020-11-06 11 17 55](https://user-images.githubusercontent.com/3808959/98356099-61b30b00-2023-11eb-9b64-a8cc04b775d0.jpg)
![2020-11-06 11 18 02](https://user-images.githubusercontent.com/3808959/98356121-68418280-2023-11eb-9e7c-8b35cbf562bb.jpg)

Screenshot of unsuccessfully adding the dimmer switch:
![2020-11-06 11 25 26](https://user-images.githubusercontent.com/3808959/98356137-6e376380-2023-11eb-9498-93836170080a.jpg)

**Comment by espenjohannessen** [comment]
I also just noticed that my dimmer switch is the exact same as mentioned in #1, so perhaps that's why I'm not able to add it at all?

**Comment by maginawin** [comment]
Hi @espenjohannessen 

I think you have some misunderstandings about Namron, this App was released to the Homey App Store, but Homey has not reviewed it.

https://homey.app/a/net.filllip-namron/test/

I don't own these two Namron products, so I will contact Namron to give me some samples to find out the reasons and solve these problems.

**Comment by espenjohannessen** [comment]
Hi @maginawin 

Thanks for getting back to me so quickly! Sorry for jumping to conclutions here, but my dialog with the Namron Norwegian contact point, and the sales staff at the local reseller here in Norway, has been.. well.. frustrating to say the least. No one seems to know what I'm talking about, and don't make any real effort to find out, so I'm just told that something will come.. at some point.. hopefully.

Does this mean that this will be the new "offical" app for Namron devices, that they're working on "with the factory in china" as the Norwegian contact point said, and that you are developing it for them? Or is more of a community driven app that you are developing? I was in contact with Filip in the previous repository for the app you linked to, and he just said that Namron had taken of ownership of the app in Homey, but not the repo in Github. He didn't know anything more about the development.

**Comment by maginawin** [comment]
Hi @espenjohannessen 

Your feedback clearly pointed out the problem. I have already contacted the namron contact. Once I get the devices, I can get back to you soon.

Namron provides me with the devices, I added them to the Namron App, the Namron App will be maintained by me in the future. When Homey officially releases Homey v5.0, this application will be reviewed and officially released.

**Comment by espenjohannessen** [comment]
Hi @maginawin 

Thanks, that's awesome and I'm sorry if I came accross as rude. I'm just frustrated after spending so much money to get everything up and running and not getting anywhere. Now that I finally see some light at the end of the tunnel I'm confident in keeping all the stuff I've purchased and hopefully getting it up and running within a reasonable time frame.

If there's anything I can do to help get the two devices I have in house up and running I'd be happy to help. I am a developer myself, although not that familiar with Homey apps yet, but as I said: just let me know if there's anything I can do to help troubleshoot this issue!

**Comment by maginawin** [comment]
Hi @espenjohannessen 

Did you only buy these two types of device?

Dimmer Switch can be added to Homey even there is no Homey App to support it, you can try again according to the user manual.

When the device fails to be added, I will power off & repower the Homey gateway, power off & repower the device, and try again. Homey will not be 100% successful in adding the device.

**Comment by espenjohannessen** [comment]
Yes, I only have these two types of devices from Namron. I also use Homey apps for Nexa, Mill, Mitsubishi and Philips Hue, but I assume that's not relevant.

I was able to add the GU 10 bulbs by turning both the bulbs and my Homey on and off a few times, but no luck with the dimmer switch yet. It's almost as it's not going into pairing mode, but I've tried with two different dimmers and see the same behaviour on both: I can reset by holding the RESET button for 5 seconds, making the light turn red for 10 seconds, and I can make it flash blue by pushing it quickly two times, but still nothing happens during pairing. I tried the Homey app and ZigBee option to see if I can get it added as a generic device, but no luck there either.

**Comment by espenjohannessen** [comment]
.. and there I got all the dimmer switches working as well! I had no idea the ZigBee pairing process was so buggy, but after a bunch of attempts, with a few restarts in between, I was able to pair all the Namron stuff using this app. If I run into any more problems I'll report back, and if there is anything I can do to help out just let me know, otherwise I'll just thank you for the assistance and be on my way : )

**Comment by maginawin** [comment]
Hi @espenjohannessen 

Do you mean that these two devices are already working properly?

**Comment by espenjohannessen** [comment]
Yes, it looks like it. Each device took tens of attempts to get paired correctly, but once paired it works! The current state of the Namron GU10 bulbs (color, dim level, etc.) isn't always shown correctly in the Homey app, but I'll have to do some more testing to understand exactly what's supposed to happen and what's happening now. Still getting to know this thing : )

**Comment by maginawin** [comment]
@espenjohannessen 

I guess sometimes Homey adds zigbee devices that are not very stable. This problem can usually be solved by restarting Homey.
