### ISSUE TITLE
All namron devices offline after update to 2.0.11

### ISSUE THREAD

**Issue by geirjohansen** [easyhomesrc/homey_namronas#20]
All my namron devices are offline after app update to 2.0.11 and homey 5.0
I do see in the release notes that «devides may need to be added again», but this is a disaster in a big system as mine. All flows will not work, devices are hard to reach, all names and tweeks will be lost. There has to be a qucik fix, and i need it fast ! All other apps has solved the updates...

**Comment by maginawin** [comment]
Hi @geirjohansen ,

Try restarting the Namron App in "More > Apps > namron > Settings (Top right corner) > Restart App".

You can see the status of all your devices here. 
https://developer.athom.com/tools/zwave

**Comment by geirjohansen** [comment]
Hi ! 
I have tried to restart the app, and there is no result. All namrom devices are «not avalible».
I have tried to remove one dimmer and add it again, and this works, but it is a big job to do this with 30-40 devices ( with a lot of flows).

**Comment by VegardBF** [comment]
> Hi !
> I have tried to restart the app, and there is no result. All namrom devices are «not avalible».
> I have tried to remove one dimmer and add it again, and this works, but it is a big job to do this with 30-40 devices ( with a lot of flows).

Hi I had the same problem, I had to add all my devices again...... I feel your frustration but that was the only way.

**Comment by maginawin** [comment]
Hi @geirjohansen ,

What devices did you add to Homey?

I have released a new App, you can try it. Homey deprecated a Z-Wave library, I don't know if this is the cause of the problem.
https://homey.app/en-us/app/net.filllip-namron/namron/test/

**Comment by geirjohansen** [comment]
Tried the beta version, but the result is the same. Looks like i have to do it the hard way.
Very disapointed !!

**Comment by maginawin** [comment]
Hi @geirjohansen ,

What models of devices do you have, I can try again.

**Comment by geirjohansen** [comment]
I have aprox 25 pcs of the z-wave dimmer 140256 in addition to smaller qnty of 4512743, 4512714, 4512707,4512710, 4512720..

**Comment by geirjohansen** [comment]
I have now removed some dimmers and tried to reconnect, but even this is not problemfree, several dimmers are not pairing. If there is no solution in 24 hours I will contact elektroimportøren for the return of all products. If anyone from namron would like to fix this problem before i get really angry please call me +47 90021321

**Comment by maginawin** [comment]
Hi @geirjohansen ,

I tried to fix 1402756, please help me test whether the old device is working properly.

https://homey.app/a/net.filllip-namron/test/

**Comment by geirjohansen** [comment]
The new version seems to be working for the  dimmers, the nodes are «online», but quite a few units are reporting «request timeout». This is not a new problem though..

**Comment by maginawin** [comment]
Hi @geirjohansen ,

You mean 1402756 is working now, right? If you think that's OK, I'll continue to update the rest of the devices in the same way.

**Comment by geirjohansen** [comment]
Yes the 1402756 is working now.

**Comment by maginawin** [comment]
Hi @geirjohansen ,

Please test the latest version 2.1.4, whether the older devices are working properly.

https://homey.app/a/net.filllip-namron/test/

**Comment by geirjohansen** [comment]
It seems to be «working» now, after some power cyckles, reprogramming of all flows (as the devices are not recognized by the flows for some reason) and high bloodpressure. It took just 16 days to get back online. Flows are still abnormally slow, but i think this is just the crappy prosessor in homey...
