### ISSUE TITLE
1402756

### ISSUE THREAD

**Issue by prj84** [easyhomesrc/homey_namronas#21]
1402756 - with 1080 as Man ID (05/2020 batch)

Possible to add, but not possible to controll in the app.
If you get it included you can turn it on/off in the developer.athom.com with basic commands on/off. Device then respond and turns on or off even if it do not respond in the app

When trying on/off og change dim in the app you get a Unknown error, Invalid device. 

Removed and reinstalled but same error

Have waited untill LED goes out to include (after exclude)

On V5 and app 2.0.11

**Comment by maginawin** [comment]
Hi, 

Is 1402756 or 1402768? 

This week I will fix your question ASAP.

**Comment by prj84** [comment]
1402756 :-)
