### ISSUE TITLE
Namron 4512722 SR-ZV9001K8-DIM-G4

### ISSUE THREAD

**Issue by jevold** [easyhomesrc/homey_namronas#23]
When pairing the device, the only parameters available for programming a flow in Homey is battery status...
Do believe to have the latest app version, for both Homey (5.0) and Namron...

**Comment by prj84** [comment]
We have tested a bit about this and our success rate is near 100% following these steps:
- Exclude device from homey
- In the inclusion process there are two steps:
       - Exclude device
       - Please wait 5-10 sec
       - Do the inclusion step
Should then work without issues.

If you still have the same problem try to reset the device before trying again. You do this by presseing upper "|" and "O" and holding for 10 sec.

**Comment by b3ntsen** [comment]
Im experiencing the same trouble as thread starter. Ive tried removing, and re-adding but I cant get any other than battery status..Also tired adding to other apps than namrons app. But only battery status is showing up in flow cards.. Which makes this competely useless.

same problem with:  4512731 and  4512722. Help please..

**Comment by maginawin** [comment]
Hi @b3ntsen ,

Please make sure your Homey version is 5.0.0 and namron App version is 2.0.11 or higher.

Here's a demo video that creates 4512722 flow. 
https://youtu.be/N78lY61okQs

**Comment by b3ntsen** [comment]
Namron app v2.0.11 installed and used.
Homey version 5.0.0 installed and used.

**Comment by prj84** [comment]
In most cases this happens if you have the Easyhome or Heatit app installed on your homey. Try to remove these apps and install device with the Namron app.

**Comment by b3ntsen** [comment]
That solved my problem. Easyhome thought it was their products.. It's working excellent now :)
