### ISSUE TITLE
Cannot control 4512715 and no power measurements

### ISSUE THREAD

**Issue by VegardBF** [easyhomesrc/homey_namronas#25]
Hi I can add the device 4512715 to Homey app but I cannot control it. I cannot turn the switch off and on from the app. This worked fine until I updated Homey to V5 and Namron to v2.0.11. 

I have also lost the power measurements.

**Comment by maginawin** [comment]
Hi @VegardBF ,

I have fixed this problem, please test it with the following Homey Namron App.
https://homey.app/en-us/app/net.filllip-namron/namron/test/

**Comment by VegardBF** [comment]
I have installed the latest namron app. What do you mean I should do?

**Comment by maginawin** [comment]
Hi @VegardBF ,

Uninstall the namron App (More > Apps > namron > Settings > Uninstall), install the test version v2.1.1 at https://homey.app/en-us/app/net.filllip-namron/namron/test/ , you can test it first, and it will release after passing the review.

**Comment by VegardBF** [comment]
Okey but will all my devices disappear not work like last time I installed the new update? I had to remove all my namron 26 devices and add them again and update all my flows with the devices. It was incredible frustrating and too time consuming.

**Comment by maginawin** [comment]
Hi @VegardBF ,

If there's a red warning on the device icon, tell me the device type, and I can fix it by updating the app.
