### ISSUE TITLE
4512710, 4512715 & 4512724 is still very tricky to get paired - Version 2.1.4

### ISSUE THREAD

**Issue by prj84** [easyhomesrc/homey_namronas#28]
Hi!

I'm on lates test version of app (2.1.4)
Trying to get 4512715 and 4512724 paired. But still have a success rate of 1 of 10.

I'm waiting 5-10 sec between stages in inclusion as you have described. 

Inclusion process times out after both exclusion and inclusion.

Batch number on 4512715 - 0520
Batch number on 4512724 - 0720 (200719V1)

**Comment by maginawin** [comment]
Hi @prj84 ,

What's the success rate when you remove the Namron App and then add them with Homey default Z-Wave?

**Comment by prj84** [comment]
Hi!

Just tested now i now. 10 out of 10 times without Namron app installed.

**Comment by maginawin** [comment]
Hi @prj84 ,

Does that mean it's Homey or device problem? The Namron App doesn't have good idea to solve this problem.

**Comment by prj84** [comment]
Hmm. not sure. Since it pairs with no problem without the Namron app installed it seems to be a app problem.

**Comment by prj84** [comment]
Seems that 4512710 also have the same problem. We get a lot of comments on the app that these devices have issues.

Issues is:
- Not possible to add (just one out of 10 times)
- Not possible to operate after it is added.

**Comment by maginawin** [comment]
Hi @prj84 ，

They pair with no problem without the Namron app installed? This is not the same as my test results.

**Comment by maginawin** [comment]
Hi @prj84 ,

My test environment:

Homey App version: 6.3.1.670
Homey version: 5.0.2
Homey namron App: v2.1.6

4512715, 5/6 success rate with the namron App.
4512724, 5/6 success rate with the namron App.

4512715, produced in Jan 19th, 2021
4512724, produced in Jun 29th, 2020

The production date of the devices is indicated in following picture.

![IMG_0017](https://user-images.githubusercontent.com/8154155/111729067-28c85400-88a9-11eb-9058-0434bb330e43.JPG)

**Comment by prj84** [comment]
![D2CA6297-33CD-4E81-9B09-4C07EE6E4554](https://user-images.githubusercontent.com/35060010/111746697-aaf74f00-888e-11eb-9656-c94531885086.jpeg)

This is the devices I’m using. I have updated to latest app version. Same issues and seccess rate

**Comment by maginawin** [comment]
Hi @prj84 ,

I updated driver for 4512715, please help me test the success rate of adding 4512715 to Homey.

v2.1.7
https://homey.app/a/net.filllip-namron/test/

**Comment by prj84** [comment]
Hi! 

I have tried new version of app. 4512715 added 5/6 times with 2.1.7 version of app.
Still same issue with 4512724. This also doesn't update it's power measure after inclusion. Maybe a reporting is missing?

**Comment by maginawin** [comment]
Hi @prj84 ,

I made the same update to 4512710, 4512724, please test them. https://homey.app/a/net.filllip-namron/test/

This is the screenshots of the 4512724 power measure.
![4512724_power](https://user-images.githubusercontent.com/8154155/111855958-8a98c480-8962-11eb-99d6-91a700bad467.jpg)
