### ISSUE TITLE
Feedback (triggers?) from dimmer switches

### ISSUE THREAD

**Issue by espenjohannessen** [easyhomesrc/homey_namronas#3]
As mentioned in a previous issue I've gotten my rotary dimmer switches up and running, but I'm having issues with my Flows since the dimmer switches don't update their current state (on, off and dim level) back to Homey.  When I add a When card to a Flow and select one of the dimmer switch devices I get 3 available triggers (On, Off and Dimming level changed), and these triggers works when updated from Homey, but they don't work if I use the device itself to turn on, off or change dimming level.

The dimmer switch in question has product ID "Dimmer-Switch-ZB3.0" under Advanced Settings.

Is this a bug or is this just how it works?

**Comment by maginawin** [comment]
Hi @espenjohannessen 

Does the status of the device on Homey update  when use the device itself to turn on, off or change dimming level?

If not, means the device itself does not report status changes to Homey, so triggers cannot be activated.

**Comment by espenjohannessen** [comment]
No, it doesn't look like it, but I have seen forum discussions and changesets related to this switch and zigbee2mqtt indicating that on, off and brightness should be communicated from the device back to the zigbee network. In the forum the user wrote (translated from Norwegian): "Works great with zigbee2mqtt. It even updates in the system when you use the physical button."

His zigbee2mqtt implementation can be found here: https://github.com/Koenkk/zigbee-herdsman-converters/issues/983

**Comment by maginawin** [comment]
Hi @espenjohannessen ,

The latest App should solve this issue, and maybe you need to add the device again.
