### ISSUE TITLE
Dåelig respons

### ISSUE THREAD

**Issue by Martinoaa** [easyhomesrc/homey_namronas#32]
Har i lang tid brukt en annen namron app for å få enhetene inn unsecure. Dette har fungert EKSTREMT bra. 

Men valgte å gå over til den orginale namorn appen nå i V5. Har vellyket lagt til alle lampene på nytt. Men opplever hele tiden at det er noen lamper som ikke svarer. Da må jeg slå av og på lyset 1-2 ganger før det skjer noe. 

Har flow for å slå av alt lys, ca 5-10 lamper. Opplever stort sett konstant at 2-3 lamper ikke slukker. (Det er ikke samme lampene) Har prøvd med deltay mellom kommandoene uten at det hjalp. 

Er det noe fix på dette? Regner med at namron appen legger til lamper secure. Og siden det funker veldig bra i unsecure tror jeg feilen ligger der. 

Noe som kan fikses? Ønsker helt å bruke denne originale appen og ikke noe annet "hjemmelagd"

**Comment by maginawin** [comment]
Hi @Martinoaa ,

Please tell me what devices you have, I'll check the difference between secure and un-secure.


Best regards,
Wendong Wang

**Comment by Martinoaa** [comment]
Hi

I mostly have z-wave dimmers and two of the same type in switch.
https://www.elektroimportoren.no/namron-z-wave-dimmer-400w/4512710/Product.html

To clarify I can say that I had the same problem one year ago. Back then I switched to an unofficial app to add all the devices unsecure. But i went back to this official app a couple of weeks ago after the update to V5.
I have checked all the devices and all of them is added secure. I think the solution here is to make it possible to add the devices unsecure. 





![14050EEF-693E-4DA4-8819-63ACBD1EB502](https://user-images.githubusercontent.com/78507256/112162058-fb064680-8beb-11eb-990c-5d50fc7dc044.png)
![4AFF85F2-30DF-4701-8B7D-ACE157087EB5](https://user-images.githubusercontent.com/78507256/112162064-fc377380-8beb-11eb-9ee6-118810d4d5c0.png)

**Comment by maginawin** [comment]
Hi @Martinoaa ,

I've made some updates, please do a test.

https://homey.app/a/net.filllip-namron/test/

**Comment by Martinoaa** [comment]
Thank you, i downloadet it now, and i am coming back with a update after some testing.

Can i ask what the changes are?

**Comment by Martinoaa** [comment]
Hi, @maginawin .

I have now tried your test app. 
But it is not working better, meybe a little worse.

It workes almost every time when i am controlling 1 invidual light. 

But if i for example have a flow with 4 lights only 2 light turn on. In the app all 4 light shows as ON and I have to turn them off and on to turn them on. 

I have tried to use delay so the lights dosent turn on at the same time, but it is not working better. 

I can also mention that it is only the namron products I have trouble with, all other lights work.
I have also gone over all the devices in devloper settings to make sure that all the devices have good coverage.

Hope we can find a solution. I know of many people who use apps other than this one to get their devices insecure. But I hope I can use this app😃

**Comment by maginawin** [comment]
Hi @Martinoaa ,

Are devices that don't work properly in the flow already in insecure mode? Are devices that don't work randomly?

**Comment by Martinoaa** [comment]
Hi, my github account dident work, so I answer here.

Yes my the lights that work and dosent work are randomly. All my lights is added in secure. 

But i think it would have worked better if the lights was added unsecure. I didt have dem unsecure with an unofficial app before. And all my lights worked all the time. 

--
Mvh Martin Omland Aasrum
Tlf: 47604510

**Comment by maginawin** [comment]
Hi,

Maybe you need to remove your devices and add them again, the they'll become unsecure mode.

**Comment by maginawin** [comment]
Hi @Martinoaa <https://github.com/Martinoaa> ,

Maybe you need to remove your devices and add them again, then they'll become unsecure mode.

**Comment by Martinoaa** [comment]
Okay, so the test app you gave me should add the devices unsecure? 

I am gong to try re delete and add the lights again.

I Will come back to you with the results 
--
Mvh Martin Omland Aasrum
Tlf: 47604510

**Comment by Martinoaa** [comment]
Hi! 

The latest app you sendt me works realy good! 
All my lamps is now unsecure! 
I havend had any problems with the latest app.



Thans for the updated app!

--
Mvh Martin Omland Aasrum
Tlf: 47604510

**Comment by maginawin** [comment]
Hi @Martinoaa ,

I'm glad your problem has been solved, thanks for your support.

**Comment by geirjohansen** [comment]
Hi !
Finally someone adressed this major problem with a solution, thank you @Martinoaa. This seems to work good in my system as well. @maginawin the 8 button z-wave switch is still added in secure mode, can you please make all products add in unsecure ( on even better; give us the possibilty to choose !). And if this would be possible to do without removing and adding all devices, it would be magical !
