### ISSUE TITLE
4512707 RGBW

### ISSUE THREAD

**Issue by FranKeRS76** [easyhomesrc/homey_namronas#36]
Tried to install this in RGBW mode. But I always get the errormessage no driver installed. And it is installed as generic Zigbee-device.

**Comment by maginawin** [comment]
Hi @FranKeRS76 ,

Can you provide the Manufacturer ID, Product Type ID, Product ID to me? They are in Device -> Settings -> Advance page.

**Comment by FranKeRS76** [comment]
Hi.

These are the only two listed under Zigbee device info:

Manufacturer-ID: NAMRON AS
Product-ID: HK-ZD-RGB-A

No Product Type-ID
![Screenshot_20210412-182844](https://user-images.githubusercontent.com/82232455/114430108-62e1f880-9bbe-11eb-9236-d5193ac421cc.jpg)

**Comment by maginawin** [comment]
Hi @FranKeRS76 ,

I've fixed this issue, you can install the test App for testing, please re-add the device for testing.

https://homey.app/a/net.filllip-namron/test/

**Comment by FranKeRS76** [comment]
That worked perfectly.

Thanks :)
