### ISSUE TITLE
Namron 4512721

### ISSUE THREAD

**Issue by Oysteinsf** [easyhomesrc/homey_namronas#43]
Hi! I’m unable to Connect the Namron 4512721 to my homey with the Namron 2.1.4 app. The Namron Controller is in pair mode, but it won’t be found in the Namron app. I’ve tried with different Namron 4512721 devices, but the same result. I dont have the easyhome-app installed. Any tips on how to figure it out?

**Comment by maginawin** [comment]
Hi @Oysteinsf ,

Please provide me with the device information that is located in [Edit device] -> [Advance Settings].

![device_information](https://user-images.githubusercontent.com/8154155/124449661-3ea94880-ddb6-11eb-8345-24832d190bc8.PNG)

**Comment by Oysteinsf** [comment]
> Hi @Oysteinsf ,
> 
> Please provide me with the device information that is located in [Edit device] -> [Advance Settings].
> 
> ![device_information](https://user-images.githubusercontent.com/8154155/124449661-3ea94880-ddb6-11eb-8345-24832d190bc8.PNG)

The namron app and the device won’t pair, so I’m unable to supply any other Information than the information printed on the device. It’s also a zigbee device.

**Comment by maginawin** [comment]
Hi @Oysteinsf ,

Here is the pairing steps, will the LED indicator turns on?

`Press and hold down both Reset and Pair buttons until the LED indicator turns on. Release both button and immediately press the Pair (top right) button on the top right corner.`

Here is the reset steps, reset the device, then remove the battery and reload it. Add the device again.

`Press and hold down both Reset and Pair buttons until the LED indicator turns on. Release both button and immediately press the Reset button (top left) 5 times.`

**Comment by Oysteinsf** [comment]
Thnx, but I’ve tried this several times and with two different devices. The device is blinking like it is in pairing mode, but no pairing is made. I’ve tried to put the device close to homey and further away, but it still won’t pair.

**Comment by maginawin** [comment]
Hi @Oysteinsf ,

Have you tried restarting (re-power) Homey? What's your Homey firmware version?

**Comment by Oysteinsf** [comment]
> Hi @Oysteinsf ,
> 
> Have you tried restarting (re-power) Homey? What's your Homey firmware version?

Thnx so far!

I’ve tried both restarting from the homey app and just remove the power, but it still won’t work. 

I have version 7 of homey. 

![7C59297B-ADB8-4FEF-94F7-EEA110C6E028](https://user-images.githubusercontent.com/86929919/124489159-fdfb0080-ddb0-11eb-8f16-f5d1608f01ee.jpeg)
![3EEEA425-CF5B-48F4-AB0B-92D4A3539E0C](https://user-images.githubusercontent.com/86929919/124489162-ff2c2d80-ddb0-11eb-9f72-2ab51ece4f4f.jpeg)

**Comment by Oysteinsf** [comment]
I tried to reset the Zigbee network.
