### ISSUE TITLE
Feil etter oppdatering til v 2.2.7

### ISSUE THREAD

**Issue by gyldenst** [easyhomesrc/homey_namronas#48]
Takk for en flott app :-) Etter at homey oppdaterte appen til 2.2.7 fungerer ingen z-wave veggkontaktene lengre. Har installert de på nytt, men ingen virker.  (4512722)

**Comment by easyhomesrc** [comment]
Hi @gyldenst ,

I have fixed this issues in v2.2.8, here is the beat version, please have a test. It will be published on home.app after it passes Homey's review.

https://homey.app/a/net.filllip-namron/test/

**Comment by gyldenst** [comment]
Thanks. v2.2.8 fixed this problem.
