### ISSUE TITLE
Homey 5

### ISSUE THREAD

**Issue by bardnilsen** [easyhomesrc/homey_namronas#6]
Hi,

I have just upgraded to Homey 5.0.0-rc.47 and my devices using easyhome stoppet working.
Should it work? / will you supsport Homey 5?

Right now i am trying to add the Namron 4512702 but gets added as an generic Zigbee device, but does not work..

The Namron 4512700 is also added as Generic Zigbee device, and works with on/off, but now dimming.

**Comment by bardnilsen** [comment]
diagnostic report 46db1f04-f8af-4730-9602-90c70a273e4c

**Comment by maginawin** [comment]
Hi @bardnilsen ,

We have supported Homey 5.0.0-rc.47, Please go to the following URL to install it. Please delete EasyHome and remove your device before testing

https://homey.app/en-us/app/net.filllip-namron/namron/test/
