### ISSUE TITLE
Update the app in Homey App Store ?

### ISSUE THREAD

**Issue by runesig** [easyhomesrc/homey_namronas#63]
I can see that the app code has been updated several times by new commits. Are you going to update the Homey App Store too? Its still version 2.2.8 there

**Comment by maginawin** [comment]
Hi @runesig ,

Yes, I'm going to update to the Homey App Store this week after completing the improvements that Homey requires.

**Comment by runesig** [comment]
The app have received several updates so no need for this issue any longer. Thanks!
