### ISSUE TITLE
Wall plug 4512717 not reporting power

### ISSUE THREAD

**Issue by HaraldRex** [easyhomesrc/homey_namronas#7]
I have the wall plug (4512717) in use for a couple of days using app version 2.0.7.
It works for on/off, but it does not report power or energy (measure_power and meter_power never change from "null").
I have tried with loads up to 2kw.

Homey fw: v5.0.0-rc.47

**Comment by HaraldRex** [comment]
Hi!

This issue still remains on Homey fw v5.0.0-rc.57

"measure_power" and "meter_power" stay fixed at "null" (A fibaro Wall plug I also have, immediately shows "0" (or whatever values is consumed), never "null")

**Comment by maginawin** [comment]
@HaraldRex 

Hi, I have applied for the same device for testing, and I'll notify you again once there is a result.

**Comment by HaraldRex** [comment]
@maginawin - If there is anything I can do to help debugging the issue, please let me know.

**Comment by maginawin** [comment]
Hi @HaraldRex ,

4512717 now supports reporting power, and maybe you need to add the device again.

**Comment by HaraldRex** [comment]
Hi @maginawin - thank you for the effort! ...however; it still does not report power. (I have had it plugged into a heating panel all day). Before testing I removed and re-paired the plug using the latest test version.
It has changed from reporting "null" to "0" (in the developer interface)
