### ISSUE TITLE
Namron Z-wave switch not working

### ISSUE THREAD

**Issue by annern55** [easyhomesrc/homey_namronas#8]
Hello, 
It seems newer versions of the Z-wave switch is not working with Homey. I have tested numerous dimmer switches to make sure one was not at fault. An older pill that I have is working as it should. The error message it gives me is: "sorry can not add device, try again later" and it also adds the unit as a "z-wave device", very general and limited parameters I can setup in flows. 
Any idea what could be wrong?

**Comment by maginawin** [comment]
Hi @annern55 ,

After the device adds the unit as "z-wave device", send me the screenshot of the device's settings page.
